
services:
  bot:
    image: ${DOCKER_USERNAME}/tg_user_bot:main
    container_name: tg-user-bot
    restart: unless-stopped
    env_file:
      - .env
      #  переменные окружения при необходимости (см. ниже)
    depends_on:
      - redis
    # Для первой авторизации Telegram юзер-бота:
    stdin_open: true   # открыть STDIN
    tty: true          # выделить TTY для взаимодействия
    volumes:
      - ./session:/app  # каталог, где Telethon пишет your_session.session
  redis:
    image: redis/redis-stack-server:latest  # Redis Stack (включает RediSearch)
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./scripts:/scripts

volumes:
  redis_data:
