name: Deploy to VPS

# Срабатывает после успешного завершения сборки и публикации образа
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host:             ${{ secrets.VPS_HOST }}
          port:             ${{ secrets.VPS_PORT }}
          username:         ${{ vars.VPS_USER }}
          key:              ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            # Переходим в директорию проекта
            cd /home/deploy/tg_user_bot || exit 1

            # Выкачиваем свежий образ из реестра
            docker compose pull

            # Останавливаем и удаляем старые контейнеры
            docker compose down

            # Запускаем новые контейнеры в фоне
            docker compose up -d

            # Инициализируем RediSearch (ждём, пока Redis станет готов)
            docker compose exec redis bash -c \
              'until redis-cli ping | grep -q PONG; do echo "Ждём Redis..."; sleep 2; done; \
               bash /scripts/init_redis_search.sh'