name: Deploy to VPS

on:
  push:
    branches: [ main ]   # деплой при пуше в ветку main (измените под свой случай)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Получение кода
        uses: actions/checkout@v3

      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /home/deploy || exit 1        # путь до папки с проектом на сервере
            if [ ! -d "tg_user_bot/.git" ]; then
            git clone git@github.com:larriantoniy/tg_user_bot.git
            fi  
            cd tg_user_bot
            git pull
                                               
            docker compose down                # останавливаем старые контейнеры
            docker compose pull || true        # (если используете образы из реестра)
            docker compose up -d --build       # пересобираем образ и запускаем контейнеры
            docker compose exec redis bash -c 'until redis-cli ping | grep -q PONG; do echo "Ждём Redis..."; sleep 2; done; bash /scripts/init_redis_search.sh'

